name: mcp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - boilerpy3==1.0.7
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cattrs==25.1.1
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - chromadb==1.0.12
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - cryptography==45.0.4
      - distro==1.9.0
      - docopt==0.6.2
      - durationpy==0.10
      - Events==0.5
      - farm-haystack==1.26.4.post0
      - fastapi==0.115.9
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fsspec==2025.5.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - idna==3.10
      - importlib_metadata==8.7.0
      - importlib_resources==6.5.2
      - inflect==7.5.0
      - Jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==33.1.0
      - langdetect==1.0.9
      - lazy-imports==0.3.1
      - markdown-it-py==3.0.0
      - MarkupSafe==3.0.2
      - mdurl==0.1.2
      - mmh3==5.1.0
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - networkx==3.5
      - nltk==3.9.1
      - num2words==0.5.14
      - numpy==2.3.0
      - oauthlib==3.3.0
      - onnxruntime==1.22.0
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-instrumentation==0.55b1
      - opentelemetry-instrumentation-asgi==0.55b1
      - opentelemetry-instrumentation-fastapi==0.55b1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentelemetry-util-http==0.55b1
      - orjson==3.10.18
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pdfminer.six==20250506
      - pdfplumber==0.11.7
      - pillow==11.2.1
      - platformdirs==4.3.8
      - posthog==5.0.0
      - prompthub-py==4.0.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pycparser==2.22
      - pydantic==1.10.22
      - pydantic_core==2.33.2
      - Pygments==2.19.1
      - pypdfium2==4.30.1
      - PyPika==0.48.9
      - pyproject_hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - PyYAML==6.0.2
      - quantulum3==0.9.2
      - rank-bm25==0.2.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-cache==0.9.8
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - sseclient-py==1.8.0
      - starlette==0.45.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - typeguard==4.4.4
      - typer==0.16.0
      - typing-inspection==0.4.1
      - typing_extensions==4.14.0
      - tzdata==2025.2
      - url-normalize==2.2.1
      - urllib3==2.4.0
      - uvicorn==0.34.3
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wrapt==1.17.2
      - zipp==3.23.0
